backend:
  name: github
  repo: micppp/www.customboy.co.uk
media_folder: static/assets
public_folder: assets
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Us"
        name: "about"
        file: "/content/about.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - label: "Delivery and Returns"
        name: "delivery"
        file: "/content/delivery.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - label: "Terms and Conditions"
        name: "terms"
        file: "/content/terms.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - label: "Privacy Policy"
        name: "privacy"
        file: "/content/privacy.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
  - label: News
    name: news
    folder: news
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: "image", label: "Cover Image", widget: "image", required: false, tagname: ""}
      - { name: body, label: Body, widget: markdown }
  - label: Tutorials
    name: tutorials
    folder: tutorials
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: "image", label: "Cover Image", widget: "image", required: false, tagname: ""}
      - { name: tools, label: Tools, widget: list }
      - label: "Difficulty"
        name: "difficulty"
        widget: "select"
        options: ["Beginner", "Intermediate", "Advanced"]
        default: "Beginner"
      - { name: body, label: Body, widget: markdown }
  - label: Product
    name: product
    folder: products
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "product"}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - label: "Console"
        name: "console"
        widget: "select"
        options: ["Game Boy", "Game Boy Color", "Game Boy Advance", "Game Boy Advance SP", "Game Boy Macro"]
        default: "Game Boy"
      - label: "Images"
        name: "images"
        widget: "object"
        fields:
          - { name: "mainimage", label: "Main Image", widget: "image", required: false, tagname: ""}
          - { name: "secondaryimage", label: "Secondary Image", widget: "image", required: false, tagname: ""}
      - label: "Sale"
        name: "sale"
        widget: "select"
        options: ["Yes", "No"]
        default: "No"
      - label: "Sold"
        name: "sold"
        widget: "select"
        options: ["Yes", "No"]
        default: "No"
      - { name: list, label: Features, widget: list }
      - { name: price, label: Price, widget: number }
      - { name: body, label: Body, widget: markdown }
